version: 0.0.{build}
skip_tags: true
image: Visual Studio 2017
before_build:
  - dotnet restore
build_script:
  - dotnet build
test_script:
  - dotnet test
on_finish:
  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))